swagger: '2.0'
info:
  description: KNMI Data Catalogue API
  version: 1.0.0
  title: KNMI Data Catalogue API
  # put the contact info for your development or API team
  contact:
    email: sdpkdc-team@knmi.nl

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers

definitions:
  $ref: spec-files/kdcgeoweb/definitions.yaml

parameters:
  $ref: spec-files/kdcgeoweb/parameters.yaml

paths:
  $ref: spec-files/kdcgeoweb/paths.yaml#/paths
      
schemes:
 - https
 
host: api.knmi.nl
basePath: /catalogus/v1
